Repository nmsprime/nmsprime, pull requests merged in 2019-02, with the labels that each got.

#598 BugFix: Cache Netelements correctly
  modules/HfcReq/Entities/NetElement.php
  resources/views/bootstrap/sidebar.blade.php
Labels: ready for review

#593 Feature/small fixes roy
  database/migrations/2019_01_11_104933_changeProductTypesToPostalDelivery.php
  modules/BillingBase/Console/ZipCommand.php
  modules/BillingBase/Entities/SettlementRun.php
  modules/BillingBase/Http/Controllers/SettlementRunController.php
  modules/BillingBase/Jobs/DeleteSettlementRun.php
  modules/HfcReq/Entities/NetElementType.php
  modules/ProvBase/Console/importTvCustomersCommand.php
  modules/ProvBase/Entities/Configfile.php
  modules/ProvVoip/Entities/Phonenumber.php
  modules/ProvVoip/Http/Controllers/PhonenumberController.php
  resources/lang/de/dt_header.php
  resources/lang/de/messages.php
  resources/lang/en/dt_header.php
  resources/lang/en/messages.php
  resources/views/Generic/edit.blade.php
Labels: ready for review

#605 Feature/import command adapt to no billing nino
  modules/ProvBase/Console/importCommand.php
  modules/ProvBase/Console/importNetUserCommand.php
Labels: ready for review

#589 Feature/ticket mail
  app/Http/Controllers/GlobalConfigController.php
  modules/Dashboard/Http/Controllers/DashboardController.php
  modules/Ticketsystem/Database/Migrations/2019_01_15_151246_addTicketConfigToGlobalConfig.php
  modules/Ticketsystem/Entities/Ticket.php
  modules/Ticketsystem/Resources/views/emails/assignticket.blade.php
  resources/lang/de/helper.php
  resources/lang/de/messages.php
  resources/lang/de/validation.php
  resources/lang/de/view.php
  resources/lang/en/helper.php
  resources/lang/en/messages.php
  resources/lang/en/validation.php
  resources/lang/en/view.php
  resources/views/errors/422.blade.php
Labels: ready for review

#573 Feature/listing invoice rearrange invoice listing
  modules/Ccc/Http/Controllers/CccUserController.php
  modules/Ccc/Resources/views/index.blade.php
  resources/views/bootstrap/blank.blade.php
Labels: ready for review

#606 relocate migration file to Ticketsystem/migrations
  modules/BillingBase/Database/Migrations/2019_01_11_104933_changeProductTypesToPostalDelivery.php
Labels: ready for review

#599 Enhanced contract form validation and some translations.
  app/AddressFunctionsTrait.php
  modules/ProvBase/Database/Migrations/2019_02_13_000100_update_Contract_birthday_nullable.php
  modules/ProvBase/Entities/Contract.php
  modules/ProvBase/Http/Controllers/ContractController.php
  modules/ProvVoip/Http/Controllers/PhonebookEntryController.php
  resources/lang/de/messages.php
  resources/lang/de/validation.php
  resources/lang/en/messages.php
  resources/lang/en/validation.php
Labels: in progress

#609 Bugfix/small fixes nino
  app/BaseModel.php
  app/Console/Commands/EnsureQueueListenerIsRunning.php
  app/Http/Controllers/BaseController.php
  modules/BillingBase/Console/SettlementRunCommand.php
  modules/BillingBase/Database/Migrations/2019_02_18_001000_update_ProductAddProportional.php
  modules/BillingBase/Database/Migrations/2019_02_21_001000_update_TablesAddIndex.php
  modules/BillingBase/Entities/Item.php
  modules/BillingBase/Entities/Product.php
  modules/BillingBase/Http/Controllers/ItemController.php
  modules/BillingBase/Http/Controllers/ProductController.php
  modules/BillingBase/Http/Controllers/SepaMandateController.php
  modules/Dashboard/Entities/BillingAnalysis.php
  modules/HfcReq/Entities/NetElement.php
  modules/ProvBase/Entities/Contract.php
  modules/ProvVoip/Entities/Mta.php
  modules/ProvVoip/Entities/Phonenumber.php
  resources/lang/de/dt_header.php
  resources/lang/de/helper.php
  resources/lang/de/messages.php
  resources/lang/en/dt_header.php
  resources/lang/en/helper.php
  resources/lang/en/messages.php
  resources/views/Generic/edit.blade.php
Labels: Ready for Review
