Repository nmsprime/nmsprime, pull requests merged in 2019-07, with the labels that each got.

#700 Bugfix in showing error message.
  modules/ProvBase/Entities/Modem.php
  modules/ProvVoip/Resources/views/Phonenumber/create.blade.php
Labels: Ready for Review

#690 Feature/sort topo modems
  modules/HfcBase/Http/Controllers/TreeErdController.php
  modules/HfcBase/Resources/views/Tree/topo.blade.php
  modules/HfcCustomer/Http/Controllers/CustomerTopoController.php
  modules/ProvBase/Entities/Modem.php
  resources/lang/de/messages.php
  resources/lang/en/messages.php
Labels: Ready for Merge

#671 Improvements and bugfixes settlement run
  app/Providers/AppServiceProvider.php
  app/helpers.php
  modules/BillingBase/Entities/EnviaCdr.php
  modules/BillingBase/Entities/Invoice.php
  modules/BillingBase/Entities/SettlementRun.php
  storage/app/config/billingbase/template/default-cdr-template.tex
  storage/app/config/billingbase/template/default-invoice-template.tex
Labels: In Progress

#707 feature/small-fixes-roy
  app/Http/Controllers/BaseController.php
  config/mail.php
  public/components/nmsprime.css
Labels: In Progress

#685 Feature/translations for provvoipenvia
  app/Console/Kernel.php
  app/Http/Controllers/BaseController.php
  modules/BillingBase/Entities/Item.php
  modules/ProvBase/Http/Controllers/ModemController.php
  modules/ProvVoip/Http/Controllers/PhonenumberManagementController.php
  modules/ProvVoipEnvia/Config/config.php
  modules/ProvVoipEnvia/Database/Migrations/2019_05_21_000100_update_EnviaContract_change_tariff_variation_type.php
  modules/ProvVoipEnvia/Entities/DtFunctionsTrait.php
  modules/ProvVoipEnvia/Entities/EnviaContract.php
  modules/ProvVoipEnvia/Entities/EnviaOrder.php
  modules/ProvVoipEnvia/Entities/ProvVoipEnvia.php
  modules/ProvVoipEnvia/Entities/ProvVoipEnviaHelpers.php
  modules/ProvVoipEnvia/Http/Controllers/EnviaContractController.php
  modules/ProvVoipEnvia/Http/Controllers/EnviaOrderController.php
  modules/ProvVoipEnvia/Http/Controllers/ProvVoipEnviaController.php
  modules/ProvVoipEnvia/Providers/ProvVoipEnviaServiceProvider.php
  modules/ProvVoipEnvia/Resources/lang/de/help.php
  modules/ProvVoipEnvia/Resources/lang/de/messages.php
  modules/ProvVoipEnvia/Resources/lang/de/view.php
  modules/ProvVoipEnvia/Resources/lang/en/help.php
  modules/ProvVoipEnvia/Resources/lang/en/messages.php
  modules/ProvVoipEnvia/Resources/lang/en/view.php
  modules/ProvVoipEnvia/Resources/views/EnviaOrder/index.blade.php
  modules/ProvVoipEnvia/Resources/views/ProvVoipEnvia/actions.blade.php
  phpunit_prepare.sh
  public/components/nmsprime.css
  resources/lang/de/dt_header.php
  resources/lang/de/helper.php
  resources/lang/de/messages.php
  resources/lang/de/view.php
  resources/lang/en/dt_header.php
  resources/lang/en/helper.php
  resources/lang/en/messages.php
  resources/lang/en/view.php
Labels: Ready for Review

#710 bugfix/small-fixes-nino
  modules/HfcCustomer/Http/Controllers/CustomerTopoController.php
Labels: Ready for Review

#716 feature/overdue-debts
  Install/files/nmsprime.log
  modules/BillingBase/Entities/SepaMandate.php
  modules/BillingBase/Entities/SettlementRun.php
  modules/Dunning/Entities/Debt.php
  modules/Dunning/Entities/DefaultTransactionParser.php
  modules/Dunning/Entities/SpkTransactionParser.php
  modules/Dunning/Entities/TransactionParser.php
  modules/Dunning/Entities/TransactionParserEngine.php
  modules/Dunning/Resources/lang/de/messages.php
  modules/Dunning/Resources/lang/en/messages.php
  resources/lang/de/dt_header.php
  resources/lang/en/dt_header.php
Labels: Ready for Review

#720 feature/small-fixes-nino
  modules/BillingBase/Database/Migrations/2019_06_13_000100_update_SettlementRunAddExecutionTimestamp.php
  modules/BillingBase/Entities/SettlementRun.php
  resources/lang/de/dt_header.php
  resources/lang/en/dt_header.php
Labels: Ready for Review

#681 Feature/regenerate cpe hostnames
  modules/ProvBase/Console/cpeHostnameCommand.php
  modules/ProvBase/Database/Migrations/2019_04_24_000100_populate_tftpd_cm_log.php
  modules/ProvBase/Entities/Endpoint.php
  modules/ProvBase/Install/files/log.conf
  modules/ProvBase/Install/files/named-ddns.sh
  modules/ProvBase/Install/files/nmsprime-provbase.conf
  modules/ProvBase/Providers/ProvBaseServiceProvider.php
Labels: Needs Testing

#731 Feature/cacti performance
  Install/after_install.sh
  Install/after_upgrade.sh
  Install/config.cfg
  Install/files/tmpfiles.conf
  Install/module_after_install.sh
  Install/module_after_upgrade.sh
  modules/ProvBase/Entities/Modem.php
  modules/ProvMon/Console/cacti/cacti_host_template_cablemodem.xml
  modules/ProvMon/Console/cacti/ss_docsis.php
  modules/ProvMon/Console/cactiCommand.php
  modules/ProvMon/Database/Migrations/2019_07_22_000100_install_use_modempoller_nmsprime.php
  modules/ProvMon/Install/after_install.sh
  modules/ProvMon/Install/config.cfg
  modules/ProvMon/Install/files/cron-cacti-nmsprime
  modules/ProvMon/Install/files/modempoller-nmsprime.sh
  modules/ProvMon/Install/files/tmpfiles.conf
Labels: Ready for Review

#733 feature/small-fixes-nino
  modules/BillingBase/Entities/Invoice.php
  modules/BillingBase/Entities/SettlementRun.php
  modules/Dunning/Install/config.cfg
Labels: Ready for Review

#739 Bugfix/small fixes nino
  app/BaseModel.php
  app/GlobalConfig.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/BaseController.php
  app/Providers/ExtendedValidatorServiceProvider.php
  app/User.php
  app/extensions/validators/ExtendedValidator.php
  database/migrations/2019_07_01_163135_setEmptyStringsToNull.php
  modules/BillingBase/Entities/BillingBase.php
  modules/BillingBase/Entities/SepaMandate.php
  modules/Dunning/Entities/Debt.php
  modules/Dunning/Entities/Dunning.php
  modules/HfcCustomer/Console/MpsCommand.php
  modules/HfcCustomer/Entities/Mpr.php
  modules/HfcCustomer/Jobs/MpsJob.php
  modules/HfcReq/Entities/NetElement.php
  modules/PropertyManagement/Providers/PropertyManagementServiceProvider.php
  modules/ProvBase/Entities/Contract.php
  modules/ProvBase/Entities/Modem.php
  modules/ProvBase/Entities/ProvBase.php
  modules/ProvBase/Http/Controllers/ContractController.php
  modules/Ticketsystem/Entities/TicketType.php
  resources/lang/de/messages.php
  resources/lang/en/messages.php
Labels: Ready for Review

#717 Feature/modules dashboards
  app/Http/Controllers/Auth/AbilityController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/UserController.php
  app/Http/Controllers/BaseViewController.php
  app/Http/Controllers/GlobalConfigController.php
  app/User.php
  config/base.php
  database/migrations/2019_07_07_181904_create_column_initial_dashboard_to_users_table.php
  database/migrations/2019_07_18_110517_add_alerts_fields_to_globalconfig_table.php
  modules/BillingBase/Http/Controllers/BillingBaseController.php
  modules/BillingBase/Resources/views/index.blade.php
  modules/BillingBase/Resources/views/panels/contract_analytics.blade.php
  modules/Dashboard/Http/Controllers/DashboardController.php
  modules/Dashboard/Resources/panels/news.blade.php
  modules/Dashboard/Resources/views/index.blade.php
  modules/Dashboard/Resources/views/panels/news.blade.php
  modules/Dashboard/Resources/views/timeline/logs.blade.php
  modules/Dashboard/Resources/views/widgets/quickstart.blade.php
  modules/HfcBase/Entities/IcingaObject.php
  modules/HfcBase/Http/Controllers/HfcBaseController.php
  modules/HfcBase/Resources/views/index.blade.php
  modules/HfcReq/Database/Migrations/2019_07_29_000100_update_Netelement_add_id_name.php
  modules/HfcReq/Entities/NetElement.php
  modules/ProvBase/Http/Controllers/ProvBaseController.php
  modules/ProvBase/Resources/views/index.blade.php
  modules/ProvBase/Resources/views/widgets/quickstart.blade.php
  modules/ProvVoip/Http/Controllers/ProvVoipController.php
  modules/ProvVoip/Resources/views/index.blade.php
  modules/ProvVoip/Resources/views/widgets/quickstart.blade.php
  modules/Ticketsystem/Resources/views/dashboard.blade.php
  public/components/nmsprime.css
  resources/lang/de/view.php
  resources/lang/en/view.php
  resources/views/Layout/default.blade.php
  resources/views/bootstrap/sidebar.blade.php
Labels: Needs Adaptions
