Repository nmsprime/nmsprime, pull requests merged in 2019-06, with the labels that each got.

#694 Upgrade laravel to 5.4
  app/Http/Controllers/BaseController.php
  app/Http/Controllers/BaseViewController.php
  app/Http/Controllers/GuiLogController.php
  app/Providers/AppServiceProvider.php
  app/Providers/EventServiceProvider.php
  app/extensions/html/FormBuilder.php
  app/extensions/html/HtmlServiceProvider.php
  composer.json
  config/app.php
  config/datatables.php
  config/excel.php
  config/tinker.php
  database/migrations/2018_05_14_165239_create_bouncer_tables.php
  database/migrations/2018_05_18_000100_install_php_config_base.php
  database/migrations/2018_09_28_000100_install_remove_self_handling.php
  database/seeds/AuthuserTableSeeder.php
  modules/BillingBase/Console/fetchBicCommand.php
  modules/BillingBase/Database/Migrations/2019_01_11_104933_changeProductTypesToPostalDelivery.php
  modules/BillingBase/Providers/BillingBaseServiceProvider.php
  modules/Ccc/Database/Migrations/2016_11_22_000100_update_CccAuthusersRename_table.php
  modules/Ccc/Database/Migrations/2017_10_04_000100_update_CccAuthuserMove_table.php
  modules/Ccc/Http/Controllers/CccController.php
  modules/Ccc/Http/Controllers/CccUserController.php
  modules/Dashboard/Http/Controllers/DashboardController.php
  modules/HfcCustomer/Console/MpsCommand.php
  modules/HfcCustomer/Entities/Mpr.php
  modules/HfcSnmp/Http/Controllers/IndicesController.php
  modules/ProvBase/Database/Migrations/2018_04_05_000100_install_named_ddns.php
  modules/ProvBase/Database/Migrations/2018_06_25_000100_install_dhcpd_rename.php
  modules/ProvBase/Database/Migrations/2018_07_30_000100_install_dhcpd_default_network.php
  modules/ProvBase/Entities/Contract.php
  modules/ProvBase/Entities/Endpoint.php
  modules/ProvBase/Entities/Modem.php
  modules/ProvBase/Http/Controllers/EndpointController.php
  modules/ProvBase/Http/Controllers/IpPoolController.php
  modules/ProvBase/Http/Controllers/ModemController.php
  modules/ProvMon/Console/cacti/ss_docsis_cmts_cm_count.php
  modules/ProvMon/Database/Migrations/2018_05_18_000100_install_php_config_provmon.php
  modules/ProvMon/Database/Migrations/2018_09_06_000100_install_update_cisco_cmts_template.php
  modules/ProvVoip/Database/Migrations/2017_06_21_000001_update_TRCClass_table_make_trc_id_nullable.php
  modules/ProvVoip/Http/Controllers/MtaController.php
  modules/ProvVoipEnvia/Entities/ProvVoipEnvia.php
  modules/ProvVoipEnvia/Http/Controllers/EnviaContractController.php
  modules/ProvVoipEnvia/Http/Controllers/EnviaOrderController.php
  modules/ProvVoipEnvia/Http/Controllers/EnviaOrderDocumentController.php
  modules/VoipMon/Database/Migrations/2016_06_10_152756_create_Cdr_table.php
Labels: Ready for Review

#664 feature/small-fixes-roy
  modules/ProvMon/Http/Controllers/ProvMonController.php
  modules/ProvMon/Resources/views/spectrum-analysis.blade.php
Labels: In Progress

#683 bugfix/small-fixes-nino
  modules/BillingBase/Entities/Item.php
  modules/BillingBase/Http/Controllers/SettlementRunController.php
  modules/HfcSnmp/Http/Controllers/SnmpController.php
  storage/app/config/billingbase/bic_de.csv
Labels: Ready for Merge
