Repository nmsprime/nmsprime, pull requests merged in 2019-10, with the labels that each got.

#763 Feature/modems cmts support checks
  app/Console/Kernel.php
  app/Http/Controllers/BaseViewController.php
  modules/ProvBase/Console/HardwareSupportCommand.php
  modules/ProvBase/Database/Migrations/2019_05_29_014631_add_field_support_state_to_modem_table.php
  modules/ProvBase/Database/Migrations/2019_05_29_014716_add_field_support_state_to_cmts_table.php
  modules/ProvBase/Entities/Cmts.php
  modules/ProvBase/Entities/Modem.php
  modules/ProvBase/Http/Controllers/CmtsController.php
  modules/ProvBase/Http/Controllers/ModemController.php
  modules/ProvBase/Providers/ProvBaseServiceProvider.php
  resources/lang/de/helper.php
  resources/lang/en/dt_header.php
  resources/lang/en/helper.php
Labels: Needs Adaptions

#780 Feature/overdue debts
  modules/BillingBase/Entities/SettlementRun.php
  modules/BillingBase/Http/Controllers/SettlementRunController.php
  modules/BillingBase/Resources/views/SettlementRun/files.blade.php
  modules/BillingBase/Resources/views/SettlementRun/logs-table.blade.php
  modules/OverdueDebts/Console/ParseMt940.php
  modules/OverdueDebts/Database/Migrations/2019_09_24_000100_update_DebtChangeColumns.php
  modules/OverdueDebts/Entities/DebtImport.php
  modules/OverdueDebts/Entities/DefaultTransactionParser.php
  modules/OverdueDebts/Entities/Mt940Parser.php
  modules/OverdueDebts/Entities/TransactionParser.php
  modules/OverdueDebts/Http/Controllers/DebtController.php
  modules/OverdueDebts/Http/routes.php
  modules/OverdueDebts/Jobs/ParseMt940.php
  modules/OverdueDebts/Providers/OverdueDebtsServiceProvider.php
  modules/OverdueDebts/Resources/lang/de/help.php
  modules/OverdueDebts/Resources/lang/de/messages.php
  modules/OverdueDebts/Resources/lang/de/view.php
  modules/OverdueDebts/Resources/lang/en/messages.php
  modules/OverdueDebts/Resources/lang/en/view.php
  modules/ProvBase/Entities/Contract.php
Labels: Ready for Merge

#759 Feature/small fixes nino
  app/Http/Controllers/GuiLogController.php
  app/extensions/html/FormBuilder.php
  database/migrations/BaseMigration.php
  modules/BillingBase/Database/Migrations/2019_09_24_001000_changeFloatToDecimal.php
  modules/Dashboard/Resources/views/timeline/logs.blade.php
  modules/HfcCustomer/Http/Controllers/CustomerTopoController.php
  modules/ProvBase/Entities/Contract.php
  resources/views/Generic/index.blade.php
Labels: Ready for Merge

#757 bugfix/small-fixes-ole
  app/Console/Kernel.php
  modules/HfcCustomer/Console/ModemRefreshCommand.php
  modules/HfcCustomer/Providers/HfcCustomerServiceProvider.php
  modules/HfcReq/Install/config.cfg
  modules/ProvBase/Entities/Modem.php
  modules/ProvMon/Console/cacti/ss_docsis.php
  modules/ProvMon/Install/after_install.sh
  modules/ProvMon/Install/files/modempoller-nmsprime.sh
  modules/ProvVoip/Entities/Mta.php
Labels: Ready for Merge

#785 feature/small-fixes-nino
  app/Http/Controllers/Auth/UserController.php
Labels: Ready for Merge

#783 bugfix/small-fixes-nino
  modules/HfcCustomer/Http/Controllers/CustomerTopoController.php
Labels: Ready for Merge

#784 Feature/overdue debts
  modules/OverdueDebts/Entities/Debt.php
  modules/OverdueDebts/Entities/DebtImport.php
  modules/OverdueDebts/Entities/DefaultTransactionParser.php
  modules/OverdueDebts/Http/Controllers/DebtController.php
  modules/OverdueDebts/Jobs/DebtImportJob.php
  modules/OverdueDebts/Resources/lang/de/messages.php
  modules/OverdueDebts/Resources/lang/en/messages.php
Labels: Ready for Merge

#772 Update request of news.json
  modules/Dashboard/Http/Controllers/DashboardController.php
Labels: Ready for Merge

#779 Bugfix L5.5 Tree View
  app/Http/Controllers/BaseController.php
  database/migrations/2019_07_01_163135_setEmptyStringsToNull.php
  modules/HfcReq/Entities/NetElementType.php
  modules/ProvBase/Entities/Configfile.php
Labels: Ready for Review

#788 bugfix/small-fixes-nino
  app/Http/Controllers/BaseController.php
  database/migrations/2019_07_01_163135_set_empty_strings_to_null.php
  modules/BillingBase/Console/cdrCommand.php
  resources/views/bootstrap/sidebar.blade.php
Labels: Ready for Merge

#787 feature/small-fixes-nino
  app/BaseModel.php
  app/Http/Controllers/BaseController.php
  modules/BillingBase/Entities/EnviaCdr.php
  modules/BillingBase/Entities/SepaAccount.php
  modules/HfcBase/Http/Controllers/HfcBaseController.php
  modules/HfcBase/Http/Controllers/TreeTopographyController.php
  modules/HfcCustomer/Http/Controllers/CustomerTopoController.php
  resources/lang/de/dt_header.php
  resources/lang/en/dt_header.php
Labels: Ready for Merge

#786 feature/overdue-debts
  modules/OverdueDebts/Entities/DebtImport.php
  modules/OverdueDebts/Install/config.cfg
  modules/OverdueDebts/Install/files/overduedebts.env
Labels: Ready for Merge
